services:
  app:
    build:
      context: .
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel

  # MySQL Database Service
  db:
    image: mysql:5.7
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret      # Set the root password here
      MYSQL_DATABASE: laravel         # Default database to create
    ports:
      - "3307:3306"                   # Make sure this port is not already in use
    volumes:
      - db-data:/var/lib/mysql        # Persist database data
    networks:
      - laravel

  # Nginx Service (optional, if you want to serve with Nginx)
  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  db-data:
    driver: local
